### ISSUE TITLE
Adapting CFAT for HAT

### ISSUE THREAD

**Issue by PhuTran1005** [alireza-aghelan/IG-CFAT#1]
Thank you very much for sharing your great work.

I already replicated the HAT paper, now I try to replicate CFAT paper. I do it by copying the cfat architecture code into the HAT code, but when i run validation, it got the error about window_partition_triangular() function. I trained on DF2K dataset.
Do you have any idea about this problem when training CFAT model?

![image](https://github.com/user-attachments/assets/65ecd802-5286-460b-b8be-ecdd8435a988)

Thanks

**Comment by alireza-aghelan** [comment]
Thank you for your interest in our work.

We have not observed this problem in our experiments.
To address this issue, we recommend using the test file provided in the CFAT GitHub repository. You can find it at [https://github.com/rayabhisek123/CFAT/blob/master/test.py](url)
